OC_P9/force-app/main/default/objects/Order/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

OC_P9/force-app/main/default/objects/Order/fields/ShipmentCost__c.field-meta.xml
<CustomField>
    <fullName>ShipmentCost__c</fullName>
    <label>Shipment Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

OC_P9/force-app/main/default/classes/AP01Order.cls
public class AP01Order {

    public static void updateNetAmount(set<Id> setorderIds)
    {
       List<Order> orderList=new List<Order>();
       orderList=[Select Id,TotalAmount,NetAmount__c,ShipmentCost__c 
                  From Order
                  Where Id IN :setorderIds];
       
     //update of Net Amount of every Order based on the formula:Total Amount-Shipment Cost
       if(orderList!=null && orderList.size()>0)
       {
         for(Order ord:orderList)
         {
            ord.NetAmount__c = ord.TotalAmount - ord.ShipmentCost__c;
         }
         update orderList;
       }
    }
 }